// Generated by CoffeeScript 2.5.1
(function() {
  var newGame, place, reversi;

  reversi = require('reversi');

  newGame = function() {
    var game;
    game = new reversi.Game();
    return game;
  };

  place = function(game, row, col) {
    game.proceed(row, col);
    console.log(game.toText());
    return game;
  };

  window.newGame = newGame;

  window.place = place;

  window.reversi = reversi;

}).call(this);
